import { mkdtempSync, mkdirSync, writeFileSync, existsSync, readFileSync, watch } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
const scratch = "/tmp/apex-execution-audit-9jrqki6o";
process.chdir(scratch);
process.env.HOME = scratch;
process.env.APEX_CODE_AGENT_DIR = join(scratch, 'agent');
const { SettingsManager } = await import("/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/settings-manager.ts");
const { hasTrustRequiringProjectResources } = await import("/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/trust-manager.ts");
const { createAgentSessionServices, createAgentSessionFromServices } = await import("/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/agent-session-services.ts");
const { SessionManager } = await import("/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/session-manager.ts");
const agentDir=join(scratch,'agent'); mkdirSync(agentDir,{recursive:true});
const marker=join(scratch,'mcp-session-ran-2');
writeFileSync(join(scratch,'.mcp.json'), JSON.stringify({mcpServers:{probe:{command:process.execPath,args:['-e',`require('node:fs').writeFileSync(${JSON.stringify(marker)},'ran')`],lifecycle:'eager'}}}));
console.log('trustRequiringResources=',hasTrustRequiringProjectResources(scratch));
const settingsManager=SettingsManager.create(scratch,agentDir,{projectTrusted:false});
const services=await createAgentSessionServices({cwd:scratch,agentDir,settingsManager,resourceLoaderOptions:{noExtensions:true,noSkills:true,noPromptTemplates:true,noThemes:true}});
const {session}=await createAgentSessionFromServices({services, sessionManager:SessionManager.inMemory(scratch),tools:[]});
// Wait on a filesystem event; no model request occurs.
await new Promise((resolve,reject)=>{ const watcher=watch(scratch,()=>{if(existsSync(marker)){clearTimeout(timeout);watcher.close();resolve(undefined)}}); const timeout=setTimeout(()=>{watcher.close();reject(new Error('MCP marker absent'))},3000); if(existsSync(marker)){clearTimeout(timeout);watcher.close();resolve(undefined)} });
console.log('projectTrusted=',settingsManager.isProjectTrusted(),'mcpCommandExecuted=',existsSync(marker));
await session.dispose(); await services.close();
const {loadPolicyConfiguration}=await import("/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/policy-loader.ts");
const {VerificationTracker}=await import("/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/verification-lifecycle.ts");
const {runFormatterCommand}=await import("/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/formatter-lifecycle.ts");
const policies=loadPolicyConfiguration({projectTrusted:false,globalSettings:{schemaVersion:1,verification:[{id:'denied',executable:process.execPath,argv:['-e',"console.log('denied command ran')"],permission:'deny'}],formatter:[{id:'formatter',executable:process.execPath,argv:['-e',"require('node:fs').writeFileSync('unrelated.txt','changed')"],permission:'allow',declaredPaths:['allowed.txt']}]}});
console.log('policyParseErrors=',policies.errors);
const tracker=new VerificationTracker({workspaceRoot:scratch}); tracker.configure(policies.verification,'explicit');
console.log('deniedVerification=',JSON.stringify(await tracker.runExplicit()));
const formatter=await runFormatterCommand(policies.formatter[0],{workspaceRoot:scratch});
console.log('formatterStatus=',formatter.status,'undeclaredPaths=',formatter.mutations.undeclaredPaths,'undeclaredWritePersisted=',existsSync(join(scratch,'unrelated.txt')));
