import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fauxAssistantMessage } from "@earendil-works/pi-ai";
import { createGitCheckpoints } from "../../../packages/coding-agent/src/core/checkpoints/git-checkpoints.ts";
import { SessionManager } from "../../../packages/coding-agent/src/core/session-manager.ts";

const root = mkdtempSync(join(tmpdir(), "apex-tree-terminal-"));
const workspace = join(root, "workspace");
const agentDir = join(root, "agent");
mkdirSync(workspace);
mkdirSync(agentDir);
process.chdir(workspace);
execFileSync("git", ["init", "-b", "main"], { stdio: "ignore" });
writeFileSync(join(workspace, "tracked.txt"), "checkpointed\n");
execFileSync("git", ["add", "tracked.txt"]);
execFileSync("git", ["-c", "user.name=Terminal probe", "-c", "user.email=probe@example.com", "commit", "-m", "initial"], { stdio: "ignore" });
writeFileSync(join(agentDir, "settings.json"), JSON.stringify({ branchSummary: { skipPrompt: true } }));
const manager = SessionManager.create(workspace, join(root, "sessions"));
manager.appendMessage({ role: "user", content: "First question", timestamp: Date.now() });
const target = manager.appendMessage(fauxAssistantMessage("First answer"));
manager.appendMessage({ role: "user", content: "Second question", timestamp: Date.now() });
manager.appendMessage(fauxAssistantMessage("Second answer"));
const engine = await createGitCheckpoints(workspace, manager.getSessionId());
assert(engine);
assert(await engine.capture(target));
writeFileSync(join(workspace, "tracked.txt"), "edited\n");
const fixture = { root, workspace, agentDir, sessionFile: manager.getSessionFile(), target };
writeFileSync(join(root, "fixture.json"), JSON.stringify(fixture, null, 2));
console.log(JSON.stringify(fixture, null, 2));
