import { mkdir, writeFile, readFile, symlink } from 'node:fs/promises';
import { join } from 'node:path';
import { FilePermissionRuleStore } from "/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/permissions/store.ts";
import { evaluateToolCall } from "/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/permissions/gate.ts";
import { resolveEffectiveMode } from "/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/permissions/startup.ts";
import { createWriteToolDefinition } from "/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/tools/write.ts";
import { createReadToolDefinition } from "/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/tools/read.ts";
import { createBashPermissionSpec } from "/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/tools/bash.ts";
import { hasTrustRequiringProjectResources } from "/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/trust-manager.ts";
const cwd = "/tmp/apex-permission-audit-kbt6mo76"; process.chdir(cwd);
const store = new FilePermissionRuleStore({cwd,agentDir:join(cwd,'agent'),policyPath:join(cwd,'policy.json')});
const write = createWriteToolDefinition(cwd); const read = createReadToolDefinition(cwd);
const bashContract = {...write.contract,capabilities:new Set(['exec']), permission:createBashPermissionSpec()};
const gate = (name, params, mode='default') => evaluateToolCall(name,params,{store,getMode:()=>mode,getContract:n=>n==='write'?write.contract:n==='read'?read.contract:bashContract});
await store.apply({type:'addRules',destination:'user',rules:[{toolName:'read',behavior:'deny',ruleContent:'secret.txt'},{toolName:'bash',behavior:'allow'}]});
await writeFile(join(cwd,'secret.txt'),'private');
console.log('read exact deny',await gate('read',{path:'secret.txt'}));
console.log('read @ alias',await gate('read',{path:'@secret.txt'}));
const r = await read.execute('probe',{path:'@secret.txt'}); console.log('read @ alias content',r.content);
const rule=write.contract.permission.ruleForCall({path:'*.txt',content:''});
console.log('generated path rule',rule,'authorizes other.txt',write.contract.permission.matches(rule,{path:'other.txt',content:''}));
await symlink(join(cwd,'secret.txt'),join(cwd,'alias.txt'));
console.log('read symlink bypass',await gate('read',{path:'alias.txt'}));
await writeFile(join(cwd,'policy.json'),JSON.stringify({version:1,rules:[{toolName:'bash',behavior:'deny',ruleContent:'touch:*'}]}));
console.log('bash policy direct',await gate('bash',{command:'touch denied'}));
console.log('bash policy chain',await gate('bash',{command:'echo ok; touch denied'}));
console.log('bash policy unparseable',await gate('bash',{command:'touch denied > output'}));
await store.apply({type:'replaceRules',destination:'user',rules:[{toolName:'bash',behavior:'deny'}]});
const params={path:'.apex-code/permissions.local.json',content:JSON.stringify({version:1,rules:[{toolName:'bash',behavior:'allow'}]})};
console.log('self-write acceptEdits',await gate('write',params,'acceptEdits'));
await write.execute('probe',params);
console.log('self-granted bash',await gate('bash',{command:'echo self-granted'},'acceptEdits'));
await mkdir(join(cwd,'untrusted','.apex-code'),{recursive:true});
await writeFile(join(cwd,'untrusted','.apex-code','permissions.json'),JSON.stringify({version:1,mode:'bypassPermissions',rules:[]}));
const untrusted=new FilePermissionRuleStore({cwd:join(cwd,'untrusted'),agentDir:join(cwd,'empty-agent'),policyPath:join(cwd,'missing-policy')});
console.log('permission-only project needs trust',hasTrustRequiringProjectResources(join(cwd,'untrusted')));
console.log('permission-only project mode',resolveEffectiveMode(undefined,(await untrusted.snapshot()).modesBySource));
