import { mkdtempSync, mkdirSync, writeFileSync, existsSync, readFileSync, watch } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
const scratch = '/home/nochaserz/Documents/Coding Projects/apex-code/.apex-code/audit-review-2026-09-05/execution-scratch-corrected';
for (const key of Object.keys(process.env)) if (!["PATH", "SystemRoot"].includes(key)) delete process.env[key];
process.env.TMPDIR = scratch;
const {execFileSync}=await import('node:child_process');
execFileSync('git',['init','-q',scratch]);
process.chdir(scratch);
process.env.HOME = scratch;
process.env.APEX_CODE_CODING_AGENT_DIR = join(scratch, 'agent');
const { SettingsManager } = await import("/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/settings-manager.ts");
const { hasTrustRequiringProjectResources } = await import("/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/trust-manager.ts");
const { createAgentSessionServices, createAgentSessionFromServices } = await import("/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/agent-session-services.ts");
const { SessionManager } = await import("/home/nochaserz/Documents/Coding Projects/apex-code/packages/coding-agent/src/core/session-manager.ts");
const agentDir=join(scratch,'agent'); mkdirSync(agentDir,{recursive:true});
const marker=join(scratch,'mcp-session-ran-2');
writeFileSync(join(scratch,'.mcp.json'), JSON.stringify({mcpServers:{probe:{command:process.execPath,args:['-e',`require('node:fs').writeFileSync(${JSON.stringify(marker)},'ran')`],lifecycle:'eager'}}}));
console.log('trustRequiringResources=',hasTrustRequiringProjectResources(scratch));
writeFileSync(join(agentDir,'settings.json'), JSON.stringify({policies:{schemaVersion:1,verification:[{id:'denied',executable:process.execPath,argv:['-e',"console.log('denied command ran')"],permission:'deny'}],formatter:[{id:'formatter',executable:process.execPath,argv:['-e',"require('node:fs').writeFileSync('unrelated.txt','changed')"],permission:'allow',declaredPaths:['allowed.txt']}]}}));
const settingsManager=SettingsManager.create(scratch,agentDir,{projectTrusted:false});
const services=await createAgentSessionServices({cwd:scratch,agentDir,settingsManager,resourceLoaderOptions:{noExtensions:true,noSkills:true,noPromptTemplates:true,noThemes:true}});
let gateCalls = 0;
const {session}=await createAgentSessionFromServices({services, sessionManager:SessionManager.inMemory(scratch),tools:[], permissionGate:{store:{snapshot:async()=>{gateCalls++;return {rules:[],modesBySource:new Map(),errors:[]};},apply:async()=>{throw new Error('unexpected approval persistence');}},getMode:()=> 'plan'}});
// Wait on a filesystem event; no model request occurs.
await new Promise((resolve,reject)=>{ const watcher=watch(scratch,()=>{if(existsSync(marker)){clearTimeout(timeout);watcher.close();resolve(undefined)}}); const timeout=setTimeout(()=>{watcher.close();reject(new Error('MCP marker absent'))},3000); if(existsSync(marker)){clearTimeout(timeout);watcher.close();resolve(undefined)} });
console.log('projectTrusted=',settingsManager.isProjectTrusted(),'mcpCommandExecuted=',existsSync(marker));
console.log('publicVerification=',await session.requestVerification(), 'verificationRecord=',JSON.stringify(session.verificationRecord()));
const formatter=await session.runConfiguredFormatter();
console.log('publicFormatterStatus=',formatter.status,'undeclaredPaths=',formatter.mutations.undeclaredPaths,'undeclaredWritePersisted=',existsSync(join(scratch,'unrelated.txt')), 'gateCalls=',gateCalls);
await session.dispose(); await services.close();
